backend:
  name: git-gateway
  repo: mauriciabad/digital-menu-lacuina
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

locale: 'es'
site_url: https://escastell-menu.netlify.app/

media_folder: static/img
public_folder: /img

collections:
  - name: "menu"
    label: "Carta"
    folder: "src/pages/menu"
    create: true
    slug: "{{fields.lang}}"
    identifier_field: "langName"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "menu-post"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Nombre del idioma (en el propio idioma)", name: "langName", widget: "string"}
      - {label: "Código del idioma", name: "lang", widget: "string", pattern: ['^[a-z]{2}$', 'Código de idioma incorrecto']}
      - {label: "Bandera", name: "flagimage", widget: image}
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Configuración"
    create: false
    editor:
      preview: false
    files:
      - file: "src/settings.md"
        label: "General"
        name: "settings"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "settings"}
          - {label: "Web", name: "title", widget: "string"}
          - {label: "Fondo", name: "bgimage", widget: image}
          - {label: "Código del idioma predeterminado", name: "defaultLang", widget: "string", pattern: ['^[a-z]{2}$', 'Código de idioma incorrecto']}
